[package]
name = "markov_bot"
description = "A discord chat bot written in Rust"
repository = "https://github.com/TheKroni/markov-bot"
license = "MIT"
version = "1.1.0"
authors = ["Kroni"]
edition = "2021"

[dependencies]
serenity = { version="0.11.4", default-features = false, features = ["cache", "client", "gateway", "rustls_backend", "model", "unstable_discord_api", "voice"] }
# requires yt-dlp, opus and ffmpeg in order for voice commands to work
songbird = {version="0.3.0", features=["builtin-queue", "serenity", "yt-dlp"]}
tokio = { version = "1.20.0", features = ["macros", "rt-multi-thread", "signal"] }
serde_json = "1.0.82"
regex = "1.6.0"
markov_strings = "0.1.5"
dotenv = "0.15.0"
crossbeam = "0.8.1"
rayon = "1.5.3"
strum = "0.24.1"
strum_macros = "0.24.2"
rand = "0.8.5"
dashmap = {version="5.3.4", features=["serde"] }
serde = "1.0.140"
anyhow = "1.0.58"
thiserror = "1.0.31"