[package]
name = "markov_bot"
description = "A discord chat bot written in Rust"
repository = "https://github.com/TheKroni/markov-bot"
license = "MIT"
version = "1.0.2"
authors = ["Kroni"]
edition = "2021"

[dependencies]
serenity = { version="0.10.9", default-features = false, features = ["cache", "client", "gateway", "rustls_backend", "model", "unstable_discord_api"] }
tokio = { version = "1.8.0", features = ["macros", "rt-multi-thread"] }
serde_json = "1.0"
regex = "1.5.4"
markov_strings = "0.1.4"
dotenv = "0.15"
crossbeam = "0.8.1"
rayon = "1.5.1"
strum = "0.23.0"
strum_macros = "0.23.1"
rand = "0.8.4"
dashmap = {version="5.0.0", features=["serde"] }
serde = "1.0.132"

[patch.crates-io]
markov_strings = { path = "local-dependencies/markov_strings" }