[package]
name = "markov_bot"
description = "A discord chat bot written in Rust"
repository = "https://github.com/TheKroni/markov-bot"
license = "MIT"
version = "1.3.0"
authors = ["Kroni"]
edition = "2021"

[dependencies]
tokio = { version = "1.22.0", features = [
	"macros",
	"rt-multi-thread",
	"signal",
] }
serde_json = "1.0.89"
regex = "1.7.0"
markov_strings = "0.1.5"
dotenvy = "0.15.6"
crossbeam = "0.8.2"
rayon = "1.6.0"
strum = "0.25"
strum_macros = "0.25.2"
rand = "0.8.5"
dashmap = { version = "5.4.0", features = ["serde"] }
serde = "1.0.147"
anyhow = "1.0.66"
thiserror = "1.0.37"
sqlx = { version = "0.7.1", features = ["runtime-tokio-native-tls", "mysql"] }
reqwest = "0.11.13"
opentelemetry = "0.20"
opentelemetry_sdk = { version = "0.20", features = ["rt-tokio"] }
tracing = "0.1"
tracing-opentelemetry = { version = "0.21" }
tracing-subscriber = { version = "0.3", features = [
	"tracing-log",
	"env-filter",
] }
opentelemetry-otlp = "0.13"
futures = "0.3"
itertools = "0.11.0"

[dependencies.serenity]
default-features = false
features = [
	"cache",
	"client",
	"gateway",
	"rustls_backend",
	"model",
	"unstable_discord_api",
	"voice",
]
git = "https://github.com/serenity-rs/serenity"
branch = "next"

# requires yt-dlp and opus in order for voice commands to work
[dependencies.songbird]
git = "https://github.com/TheKroni/songbird"
branch = "next"
features = ["builtin-queue", "serenity"]

[dependencies.symphonia]
# version = "0.5"
features = ["aac", "mp3", "isomp4", "alac"] # ...as well as any extras you need!
# **NOTE**: For now, please use this fork in pre-releases for a key fix to
# seeking on streamed MKV/WebM files.
git = "https://github.com/FelixMcFelix/Symphonia"
branch = "songbird-fixes"

[profile.dev.package.sqlx-macros]
opt-level = 3
