[package]
name = "markov_bot"
version = "1.0.2"
authors = ["Kroni"]
edition = "2018"

[dependencies]
serenity = { version="0.10.9", default-features = false, features = ["cache", "client", "gateway", "rustls_backend", "model","framework", "standard_framework", "unstable_discord_api"] }
tokio = { version = "1.8.0", features = ["macros", "rt-multi-thread"] }
serde_json = "1.0"
regex = "1.5.4"
markov_strings = "0.1.4"
dotenv = "0.15"
crossbeam = "0.8.1"
rayon = "1.5.1"
strum = "0.21"
strum_macros = "0.21"
rand = "0.8.4"

[patch.crates-io]
markov_strings = { path = "local-dependencies/markov_strings" }