[package]
name = "markov_bot"
description = "A discord chat bot written in Rust"
repository = "https://github.com/TheKroni/markov-bot"
license = "MIT"
version = "1.1.0"
authors = ["Kroni"]
edition = "2021"

[dependencies]
tokio = { version = "1.20.0", features = [
	"macros",
	"rt-multi-thread",
	"signal",
] }
serde_json = "1.0.82"
regex = "1.6.0"
markov_strings = "0.1.5"
dotenv = "0.15.0"
crossbeam = "0.8.1"
rayon = "1.5.3"
strum = "0.24.1"
strum_macros = "0.24.2"
rand = "0.8.5"
dashmap = { version = "5.3.4", features = ["serde"] }
serde = "1.0.140"
anyhow = "1.0.58"
thiserror = "1.0.31"
sqlx = { version = "0.5.5", features = [
	"runtime-tokio-native-tls",
	"mysql",
	"offline",
] }
reqwest="0.11.11"

[dependencies.serenity]
default-features = false
features = [
	"cache",
	"client",
	"gateway",
	"rustls_backend",
	"model",
	"unstable_discord_api",
	"voice",
]
git = "https://github.com/serenity-rs/serenity"
branch = "next"

# requires yt-dlp, opus and ffmpeg in order for voice commands to work
[dependencies.songbird]
git = "https://github.com/serenity-rs/songbird"
branch = "next"
features = ["builtin-queue", "serenity"]

[dependencies.symphonia]
# version = "0.5"
features = ["aac", "mp3", "isomp4", "alac"] # ...as well as any extras you need!
# **NOTE**: For now, please use this fork in pre-releases for a key fix to
# seeking on streamed MKV/WebM files.
git = "https://github.com/FelixMcFelix/Symphonia"
branch = "songbird-fixes"

[profile.dev.package.sqlx-macros]
opt-level = 3
