[package]
name = "doki_bot"
version = "0.1.0"
authors = ["Kroni"]
edition = "2018"

[dependencies]
serenity = { version="0.10.8", default-features = false, features = ["cache", "client", "gateway", "rustls_backend", "model","framework", "standard_framework", "unstable_discord_api"] }
tokio = { version = "1.8.0", features = ["macros", "rt-multi-thread"] }
serde_json = "1.0"
regex = "1.5.4"
markov_strings = "0.1.4"
dotenv = "0.15"
druid = "0.7.0"